name: Run hola-mundo.js
run-name: Aprendiendo GitHub Actions!

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Ejecutar hola-mundo.js
        run: node hola-mundo.js
